# Generated by Django 4.2 on 2023-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["number"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="image",
            name="number",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Позиция"),
        ),
    ]
