# Generated by Django 4.1 on 2023-04-11 18:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_image_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Длинное описание"),
        ),
    ]
