# Generated by Django 4.1 on 2023-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title_text",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Заголовок"
            ),
        ),
    ]
